//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PunchInOut
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> PunchOutDate { get; set; }
        public Nullable<bool> IsPunchOut { get; set; }
        public Nullable<bool> IsPunchIn { get; set; }
        public Nullable<System.DateTime> PunchInDate { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
